### ISSUE TITLE
Params of type "***_ids" not working

### ISSUE THREAD

**Issue by VirgileGibello** [lpg2709/clickup_api#14]
Hello,
As the official documentation says : 
![image](https://github.com/lpg2709/clickup_api/assets/107399970/0cc9b504-9b40-4535-8ff5-6714533ad82a)
The API url waits a string parameter, using this key in params object cause a 500 error. This syntax of multi-value param is not currently covered by _src/utils/params.js_.
This file should detect an array-typed value and perform a loop to add `***_ids[]=xxxx` each time.

Thanks !

**Comment by lpg2709** [comment]
Hi, problem fixed on version v1.3.0: [clickup_api@1.3.0](https://www.npmjs.com/package/clickup_api/v/1.3.0)
