### ISSUE TITLE
Nice to have - Clickup api url

### ISSUE THREAD

**Issue by mcannesson** [lpg2709/clickup_api#17]
Is it possible to pass a parameter to the clickup_api constructor to change the clickup api url used ?
I need to change it to catch request in my proxy (to avoid CORS issue).

Thanks.

**Comment by lpg2709** [comment]
Hi, 

Alright, i'm gonna release this change on next update. 

Tks for the feedback.

**Comment by mcannesson** [comment]
Thanks !

**Comment by mcannesson** [comment]
Hello i've done the modification locally, do you allow me to submit the modifications ?

**Comment by lpg2709** [comment]
Hi,

Open a merge request to dev branch, so I can check the changes.

Tks.

**Comment by mcannesson** [comment]
Done here, https://github.com/lpg2709/clickup_api/pull/18
Thanks.

**Comment by lpg2709** [comment]
Changes published on version 1.4.0.

[https://www.npmjs.com/package/clickup_api/v/1.4.0](https://www.npmjs.com/package/clickup_api/v/1.4.0)
